server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: IntelliEdu
  session:
    store-type: redis
    timeout: 2592000 # 30 days expiration
    redis:
      # 禁用 Spring Session 自动配置 Redis 的行为，确保使用云服务商提供的 Redis 配置。
      # 这行配置可以防止 Spring Boot 在启动时尝试对 Redis 进行任何配置更改，从而避免潜在的连接问题或配置冲突
      configure-action: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_MYSQL_URL_INTELLIEDU}
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}
  redis:
    host: ${PROD_REDIS_HOST}
    port: ${PROD_REDIS_PORT}
    database: ${PROD_REDIS_DATABASE_INTELLIEDU}
    username: ${PROD_REDIS_USERNAME}
    password: ${PROD_REDIS_PASSWORD}
    timeout: 5000
    ssl: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: false
openai:
  token: ${OPENAI_TOKEN}
